# -*- coding: utf-8 -*-
"""fitness
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/17UoYf2sfTqU87dxgswH_jMgRiwKN2LVr
"""
import streamlit as st
st.title("🏋️ Login to Your Gym Account")
st.set_page_config(
page_title="Gym Management",
page_icon="🏋️"
)

username = st.text_input(
"Enter your username"
)

password = st.text_input(
"Enter your password",
type="password"
)

verification = [
username,
password
]

if st.button("Login"):

    if username == "Rockgym" and password == "fitness":
        st.session_state["logged_in"] = True 
        st.success("Login successful! 🎉") 
        st.rerun()

    else:

        st.error("Invalid username or password.")
if st.session_state["logged_in"]:

    st.title("🏋️ Gym Management Home")

    st.success("Login successful! 🎉")

    st.header("👤 Add Member")

    name = st.text_input("Enter member name")

    age = st.number_input("Enter age", min_value=1)

    fee = st.number_input("Enter membership fee", min_value=0.0)

    if st.button("Add Member"):
        st.success("Member added successfully!")


